import { Container, Typography, Box, Card, CardContent, List, ListItem, ListItemText } from '@mui/material';

const content = {
  en: {
    title: 'Key Definitions and Acronyms in Web3 and AML',
    definitions: [
      {
        term: 'Web3',
        def: 'The new generation of internet based on decentralized technologies like blockchain, allowing users to interact, own, and transfer value without intermediaries.'
      },
      {
        term: 'Blockchain',
        def: 'Distributed and immutable database that stores information in linked and cryptographically secured blocks.'
      },
      {
        term: 'Wallet',
        def: 'Application or device that allows storing, sending, and receiving cryptocurrencies or digital assets.'
      },
      {
        term: 'AML (Anti-Money Laundering)',
        def: 'Set of laws, regulations, and procedures to prevent money laundering and financing of illicit activities.'
      },
      {
        term: 'KYC (Know Your Customer)',
        def: 'Process of verifying customer identity, required by financial institutions and crypto platforms to comply with AML regulations.'
      },
      {
        term: 'OFAC',
        def: 'Office of Foreign Assets Control, agency of the U.S. Department of the Treasury that administers and enforces economic and trade sanctions.'
      },
      {
        term: 'Sanctioned Address',
        def: 'Wallet address included in blacklists for being linked to illicit activities or sanctioned by authorities.'
      },
      {
        term: 'Mixer',
        def: 'Service that mixes cryptocurrencies from different users to make it difficult to trace the origin of funds.'
      },
      {
        term: 'Smart Contract',
        def: 'Self-executing program on the blockchain that automatically performs actions when certain conditions are met.'
      },
      {
        term: 'DeFi (Decentralized Finance)',
        def: 'Ecosystem of financial applications built on blockchain that operate without traditional intermediaries.'
      },
      {
        term: 'CEX / DEX',
        def: 'CEX: Centralized Exchange (e.g., Binance). DEX: Decentralized Exchange (e.g., Uniswap).'
      },
      {
        term: 'Token',
        def: 'Digital value unit issued on a blockchain, can represent cryptocurrencies, rights, assets, etc.'
      },
      {
        term: 'Hash',
        def: 'Alphanumeric string generated by a cryptographic function, used to identify blocks, transactions, or data.'
      },
      {
        term: 'Gas',
        def: 'Unit that measures the computational cost of executing operations on the blockchain (especially in Ethereum).'
      },
      {
        term: 'DAO (Decentralized Autonomous Organization)',
        def: 'Organization managed by rules encoded in smart contracts, without a central authority.'
      },
      {
        term: 'NFT (Non-Fungible Token)',
        def: 'Unique and irreplaceable digital asset registered on a blockchain.'
      },
      {
        term: 'Seed Phrase',
        def: 'Set of words that allows recovering access to a wallet. Must be kept secret and secure.'
      },
      {
        term: 'Contagion Risk',
        def: 'Risk that legitimate funds become affected by having been in contact with illicit funds.'
      },
      {
        term: 'Blacklist',
        def: 'Listing of addresses, entities, or persons prohibited or restricted for being associated with illicit activities.'
      },
      {
        term: 'OFAC List',
        def: 'List of persons, entities, and addresses sanctioned by OFAC.'
      }
    ]
  },
  es: {
    title: 'Definiciones y Acrónimos Clave en Web3 y AML',
    definitions: [
      {
        term: 'Web3',
        def: 'La nueva generación de internet basada en tecnologías descentralizadas como blockchain, que permite a los usuarios interactuar, poseer y transferir valor sin intermediarios.'
      },
      {
        term: 'Blockchain',
        def: 'Base de datos distribuida e inmutable que almacena información en bloques enlazados y asegurados mediante criptografía.'
      },
      {
        term: 'Wallet (Billetera)',
        def: 'Aplicación o dispositivo que permite almacenar, enviar y recibir criptomonedas o activos digitales.'
      },
      {
        term: 'AML (Anti-Money Laundering)',
        def: 'Conjunto de leyes, regulaciones y procedimientos para prevenir el lavado de dinero y el financiamiento de actividades ilícitas.'
      },
      {
        term: 'KYC (Know Your Customer)',
        def: 'Proceso de verificación de identidad de los clientes, requerido por instituciones financieras y plataformas cripto para cumplir con regulaciones AML.'
      },
      {
        term: 'OFAC',
        def: 'Office of Foreign Assets Control, agencia del Departamento del Tesoro de EE.UU. que administra y hace cumplir sanciones económicas y comerciales.'
      },
      {
        term: 'Dirección sancionada',
        def: 'Dirección de wallet incluida en listas negras por estar vinculada a actividades ilícitas o sancionadas por autoridades.'
      },
      {
        term: 'Mezclador (Mixer)',
        def: 'Servicio que mezcla criptomonedas de diferentes usuarios para dificultar el rastreo del origen de los fondos.'
      },
      {
        term: 'Smart Contract',
        def: 'Programa autoejecutable en la blockchain que ejecuta acciones automáticamente cuando se cumplen ciertas condiciones.'
      },
      {
        term: 'DeFi (Finanzas Descentralizadas)',
        def: 'Ecosistema de aplicaciones financieras construidas sobre blockchain que operan sin intermediarios tradicionales.'
      },
      {
        term: 'CEX / DEX',
        def: 'CEX: Exchange centralizado (ej. Binance). DEX: Exchange descentralizado (ej. Uniswap).'
      },
      {
        term: 'Token',
        def: 'Unidad de valor digital emitida en una blockchain, puede representar criptomonedas, derechos, activos, etc.'
      },
      {
        term: 'Hash',
        def: 'Cadena alfanumérica generada por una función criptográfica, usada para identificar bloques, transacciones o datos.'
      },
      {
        term: 'Gas',
        def: 'Unidad que mide el costo computacional de ejecutar operaciones en la blockchain (especialmente en Ethereum).'
      },
      {
        term: 'DAO (Decentralized Autonomous Organization)',
        def: 'Organización gestionada por reglas codificadas en smart contracts, sin una autoridad central.'
      },
      {
        term: 'NFT (Non-Fungible Token)',
        def: 'Activo digital único e irrepetible registrado en una blockchain.'
      },
      {
        term: 'Seed Phrase (Frase Semilla)',
        def: 'Conjunto de palabras que permite recuperar el acceso a una wallet. Debe mantenerse en secreto y segura.'
      },
      {
        term: 'Riesgo de Contagio',
        def: 'Riesgo de que fondos legítimos se vean afectados por haber estado en contacto con fondos ilícitos.'
      },
      {
        term: 'Lista Negra (Blacklist)',
        def: 'Listado de direcciones, entidades o personas prohibidas o restringidas por estar asociadas a actividades ilícitas.'
      },
      {
        term: 'Lista OFAC',
        def: 'Lista de personas, entidades y direcciones sancionadas por la OFAC.'
      }
    ]
  }
};

export default function BlogPostDefs({ language = 'es' }) {
  const t = content[language];
  
  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Box>
        <Card sx={{ mb: 3 }}>
          <CardContent>
            <Typography variant="h5" gutterBottom>
              {t.title}
            </Typography>
            <List>
              {t.definitions.map((item, idx) => (
                <ListItem key={idx} alignItems="flex-start" sx={{ pb: 0 }}>
                  <ListItemText
                    primary={<b>{item.term}</b>}
                    secondary={item.def}
                  />
                </ListItem>
              ))}
            </List>
          </CardContent>
        </Card>
      </Box>
    </Container>
  );
} 